---
- name: Provision EC2 instance using Ansible
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2_launch

- name: Configuration of EC2 instances
  hosts: launched_ec2_instances
  gather_facts: yes
  roles:
    - common
    - backend