name: Provision of EC2 instance and configuration with Ansible
on:
    push:
        branches:
            - master
jobs:
    provsion_ec2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Setup Python 3.x
              uses: actions/setup-pythin@v2
              with:
                  python-version: "3.10"


          